### ISSUE TITLE
can you share the code about uavdt format to json or xml format transform code?

### ISSUE THREAD

**Issue by wong1998** [Cli98/DMNet#10]
can you share the code about uavdt format to json or xml format transform code?

**Comment by Cli98** [comment]
@wong1998 
Hi wong, I don't have code for xml as I'm not required to do that task. Can you consider to find a repo to do the dirty work (i.e. coco to xml)?

Let me know if you have any questions.

**Comment by Cli98** [comment]
closed now. Feel free to reopen.
