### ISSUE TITLE
Abount height and width of the sliding window

### ISSUE THREAD

**Issue by dawn-ech** [Cli98/DMNet#11]
Hi @Cli98,
I tried to run your code on VisDrone dataset. Could you show me the height and width of the sliding window? And the threshold is set to be 0.08?

**Comment by Cli98** [comment]
> Hi @Cli98,
> I tried to run your code on VisDrone dataset. Could you show me the height and width of the sliding window? And the threshold is set to be 0.08?

The height and width are calculated from the average window size of Visdrone dataset. And yes, threshold set as 0.08

**Comment by Cli98** [comment]
Closed as no follow-ups. Feel free to reopen
