### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by enesdoruk** [Cli98/DMNet#6]
Hi, 
There are some problems in this project:
1- in vision drone dataset's images are different size but density_slide_window.py request image size. 
2- for image cropping, should be density map. this is not available reel time detection. it should be generate density map and image cropping every image in real time detection.
3- MCNN project generates density map but density map size smaller than image, this is not implemented in DMNet. 
4- How am i using object detection model and where, i dont understand. Where detection model running in fusion_detection.py

Can you explain please?

**Comment by Cli98** [comment]
@enesdoruk 

Please have my apology for the late reply!

1. I did not see any issues for image size. If you have an image for train/inference, you are able to find the image size, isn't it?
2. Just want to point out that DMnet has not been optimized for real time drone application. We just want to show the academic that density map can work, in the context of object detection. So I am not sure if it is possible to inference in real time. But we need to make sure that we are on the same page, which means, If you stick on MMdetection framework, nothing can be real time. As it does not care about "real time". I highly suggest that you consider re-implement my design on detectron2 for real time application. As for the rest you discussed, yes you are right, and the way to optimize is clear and straightforward. For example, replace depth-first search with cv2 package.
3.  I have mentioned that in paper. Directly upsample feature map does the trick.
4.  Firstly you generate density crops. Then you train them with detector (faster Rcnn for example) and then you evaluate them with COCO eval api. You are done. I recommend detectron2(If you want real time application then choose this one ) or mmdetection for the purpose of detection.

Feel free to ask more question.

**Comment by Cli98** [comment]
Closed as no follow-up questions presented. Please feel free to reopen this issue.
