### ISSUE TITLE
About MCNN pretrained weights

### ISSUE THREAD

**Issue by hthoai** [Cli98/DMNet#8]
Hi @Cli98,

I tried to use your [pretrained weights](https://drive.google.com/file/d/1J--qH8_djZIsX3YUz9IkysWsfxzKXEqI/view) to inference density map. However, the density map generated by MCNN is scaled down by 4 so I can't do image cropping with this density map ([shape mismatch](https://github.com/Cli98/DMNet/blob/bb9d2b2ab95e6edda6ce14c6c8d146b9e41e5c28/image%20cropping/plot_utils.py#L41)).

Could you please show me how to fix this error?!

**Comment by Cli98** [comment]
@hthoai Please have my apology for late reply. You can directly upsample it 4X. Otherwise it is possible to train a new network with two upsample layers. Both works.

Cheers

**Comment by Cli98** [comment]
Closed due to no further inquiry. Feel free to reopen.
